# .github/workflows/deploy-react-to-iis.yml
name: Deploy React → IIS

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: [self-hosted, windows]

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'

    - name: Install dependencies & Build
      run: |
        npm ci
        npm run build

    - name: Stop any process locking the target folder
      shell: pwsh
      run: |
        $path = 'C:\webserver\thuctaptotnghiep_frontend'
        $locked = Get-Process | Where-Object {
          $_.Modules | Where-Object { $_.FileName -like "$path*" }
        }
        if ($locked) { $locked | Stop-Process -Force }

    - name: Deploy to IIS folder
      shell: pwsh
      run: |
        # dừng IIS để update file
        iisreset /stop

        # xóa thư mục cũ nếu tồn tại
        if (Test-Path 'C:\webserver\thuctaptotnghiep_frontend') {
          Remove-Item -Recurse -Force 'C:\webserver\thuctaptotnghiep_frontend'
        }

        # tạo lại thư mục và copy build vào
        New-Item -ItemType Directory -Path 'C:\webserver\thuctaptotnghiep_frontend' -Force
        Copy-Item -Path '.\build\*' -Destination 'C:\webserver\thuctaptotnghiep_frontend' -Recurse -Force

        # khởi động lại IIS
        iisreset /start
